title: New Jersey Civic Information Consortium
description: >-
  The New Jersey Civic Information Consortium supports the revitalization
  of local news and information across the state.
baseurl: "/njcivicinfo"
url: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - what-we-do.html
  - grantmaking.html
  - press-forward-nj.html
  - news-resources.html

exclude:
  - Gemfile
  - Gemfile.lock
