title: New Jersey Civic Information Consortium
description: >-
  The New Jersey Civic Information Consortium supports the revitalization
  of local news and information across the state.
baseurl: ""
url: "https://njcivicinfo.org"

logo: /assets/images/logo-favicon.png
image: /assets/images/social preview.png

twitter:
  card: summary_large_image
social:
  name: New Jersey Civic Information Consortium
  links:
    - https://www.linkedin.com/company/new-jersey-civic-information-consortium/
    - https://www.facebook.com/njcivicinfo
    - https://www.instagram.com/njcivicinfo
    - https://x.com/njcivicinfo

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/social preview.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - what-we-do.html
  - grantmaking.html
  - press-forward-nj.html
  - news-resources.html

exclude:
  - Gemfile
  - Gemfile.lock
